c files: lf = master input file
c        jif = terminal input unit number
c        jof = terminal output unit number
c        jodf= general output disk file unit number
c        ibrief = flag to control output level
c        iquiet = flag to suppress output from within procedures
      integer      lf,icf,jfcf,mpi,mpo,jif,jof,jodf,ibrief,iquiet
      common/files/lf,icf,jfcf,mpi,mpo,jif,jof,jodf,ibrief,iquiet
