      subroutine myprot(phideg,h,mh)
c
c	High order PROT routine.
c     Actual code generated by Johannes van Zeijts using
c     REDUCE.
c
      include 'impli.inc'
      include 'param.inc'
      include 'parm.inc'
      include 'pie.inc'
      double precision l,h(monoms),mh(6,6)
c
      dimension j(6)
c
      DOUBLE PRECISION B
      DOUBLE PRECISION CO
      DOUBLE PRECISION Si
c
      call clear(h,mh)
c
      B = beta
      phi = phideg*pi180
      SI = SIN(phi)
      CO = COS(phi)
c
	mh(1,1)=1.0d0/CO
      mh(2,2)=CO
      mh(2,6)=(-SI)/B
      mh(3,3)=1.0d0
      mh(4,4)=1.0d0
      mh(5,1)=SI/(B*CO)
      mh(5,5)=1.0d0
      mh(6,6)=1.0d0
c
      h(34) =(-SI)/(2.0d0*CO)
      h(43) =(-SI)/(2.0d0*CO)
      h(48) =(SI*(B**2-1))/(2.0d0*B**2*CO)
      h(105) =SI**2/(4.0d0*(SI**2-1))
      h(109) =(-SI)/(2.0d0*B*CO)
      h(114) =SI**2/(4.0d0*(SI**2-1))
      h(119) =(SI**2*(-B**2+1))/(4.0d0*B**2*(SI**2-1))
      h(132) =(-SI)/(2.0d0*B*CO)
      h(139) =(SI*(B**2-1))/(2.0d0*B**3*CO)
      h(266) =SI/(8.0d0*CO*(SI**2-1))
      h(270) =SI**2/(2.0d0*B*(SI**2-1))
      h(275) =(SI*(-2.0d0*SI**2+3))/(12.0d0*CO*(SI**2-1))
      h(280) =(SI*(2.0d0*B**2*SI**2-3.0d0*B**2-8.0d0*SI**2+9))/(
     # 12.0d0*B**2*CO*(SI**2-1))
      h(293) =SI**2/(2.0d0*B*(SI**2-1))
      h(300) =(SI**2*(-B**2+1))/(2.0d0*B**3*(SI**2-1))
      h(321) =(SI*(-4.0d0*SI**2+3))/(24.0d0*CO*(SI**2-1))
      h(326) =(SI*(4.0d0*B**2*SI**2-3.0d0*B**2-10.0d0*SI**2+9))/(
     # 12.0d0*B**2*CO*(SI**2-1))
      h(335) =(SI*(-4.0d0*B**4*SI**2+3.0d0*B**4+20.0d0*B**2*SI**2-
     # 18.0d0*B**2-16.0d0*SI**2+15))/(24.0d0*B**4*CO*(SI**2-1))
      h(588) =(SI**2*(SI**2-4))/(32.0d0*(SI**4-2.0d0*SI**2+1))
      h(592) =(SI*(SI**2+6))/(16.0d0*B*CO*(SI**2-1))
      h(597) =(SI**2*(3.0d0*SI**2-4))/(16.0d0*(SI**4-2.0d0*SI**2+
     # 1))
      h(602) =(SI**2*(-3.0d0*B**2*SI**2+4.0d0*B**2+15.0d0*SI**2-16.0d0
     # ))/(16.0d0*B**2*(SI**4-2.0d0*SI**2+1))
      h(615) =(3.0d0*SI*(-SI**2+2))/(8.0d0*B*CO*(SI**2-1))
      h(622) =(SI*(3.0d0*B**2*SI**2-6.0d0*B**2-7.0d0*SI**2+10))/(
     # 8.0d0*B**3*CO*(SI**2-1))
      h(643) =(SI**2*(5.0d0*SI**2-4))/(32.0d0*(SI**4-2.0d0*SI**2+
     # 1))
      h(648) =(SI**2*(-5.0d0*B**2*SI**2+4.0d0*B**2+17.0d0*SI**2-16.0d0
     # ))/(16.0d0*B**2*(SI**4-2.0d0*SI**2+1))
      h(657) =(SI**2*(5.0d0*B**4*SI**2-4.0d0*B**4-34.0d0*B**2*SI**2
     # +32.0d0*B**2+29.0d0*SI**2-28))/(32.0d0*B**4*(SI**4-2.0d0*SI**2+
     # 1))
      h(695) =(SI*(-7.0d0*SI**2+6))/(16.0d0*B*CO*(SI**2-1))
      h(702) =(SI*(7.0d0*B**2*SI**2-6.0d0*B**2-11.0d0*SI**2+10))/(
     # 8.0d0*B**3*CO*(SI**2-1))
      h(713) =(SI*(-7.0d0*B**4*SI**2+6.0d0*B**4+22.0d0*B**2*SI**2-
     # 20.0d0*B**2-15.0d0*SI**2+14))/(16.0d0*B**5*CO*(SI**2-1))
c
      call revf(1,h,mh)
c
      return
      end
c
c end of file
